"""Add force_password_change to UserProfile

Revision ID: 13a91e6fabcb
Revises: 9ae14c048bca
Create Date: 2026-04-11 12:15:44.686061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a91e6fabcb'
down_revision: Union[str, Sequence[str], None] = '9ae14c048bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('force_password_change', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'force_password_change')
    # ### end Alembic commands ###
