"""Add college_id to mark_entries and semester_grades

Revision ID: 2e45e2cc5e6d
Revises: 8d1877283b5a
Create Date: 2026-04-08 10:19:36.735396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e45e2cc5e6d'
down_revision: Union[str, Sequence[str], None] = '8d1877283b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('content_rating', sa.Integer(), nullable=False),
    sa.Column('teaching_rating', sa.Integer(), nullable=False),
    sa.Column('engagement_rating', sa.Integer(), nullable=False),
    sa.Column('assessment_rating', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_feedback_college_id'), 'course_feedback', ['college_id'], unique=False)
    op.create_index(op.f('ix_course_feedback_faculty_id'), 'course_feedback', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_course_feedback_id'), 'course_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_course_feedback_is_deleted'), 'course_feedback', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_course_feedback_student_id'), 'course_feedback', ['student_id'], unique=False)
    op.create_index('ix_feedback_student_subject', 'course_feedback', ['student_id', 'subject_code', 'academic_year'], unique=True)
    op.add_column('mark_entries', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_mark_entries_college_id'), 'mark_entries', ['college_id'], unique=False)
    op.create_foreign_key(None, 'mark_entries', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('semester_grades', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_semester_grades_college_id'), 'semester_grades', ['college_id'], unique=False)
    op.create_foreign_key(None, 'semester_grades', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'semester_grades', type_='foreignkey')
    op.drop_index(op.f('ix_semester_grades_college_id'), table_name='semester_grades')
    op.drop_column('semester_grades', 'college_id')
    op.drop_constraint(None, 'mark_entries', type_='foreignkey')
    op.drop_index(op.f('ix_mark_entries_college_id'), table_name='mark_entries')
    op.drop_column('mark_entries', 'college_id')
    op.drop_index('ix_feedback_student_subject', table_name='course_feedback')
    op.drop_index(op.f('ix_course_feedback_student_id'), table_name='course_feedback')
    op.drop_index(op.f('ix_course_feedback_is_deleted'), table_name='course_feedback')
    op.drop_index(op.f('ix_course_feedback_id'), table_name='course_feedback')
    op.drop_index(op.f('ix_course_feedback_faculty_id'), table_name='course_feedback')
    op.drop_index(op.f('ix_course_feedback_college_id'), table_name='course_feedback')
    op.drop_table('course_feedback')
    # ### end Alembic commands ###
