"""Pass2: Add details to Announcement, college_id to FacultyAssignment, drop SemesterGrade course FK

Revision ID: 356bb9a736ef
Revises: 9663e7989aca
Create Date: 2026-04-05 14:18:01.877956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '356bb9a736ef'
down_revision: Union[str, Sequence[str], None] = '9663e7989aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('faculty_assignments', sa.Column('college_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'faculty_assignments', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('semester_grades_course_id_fkey'), 'semester_grades', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('semester_grades_course_id_fkey'), 'semester_grades', 'courses', ['course_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'faculty_assignments', type_='foreignkey')
    op.drop_column('faculty_assignments', 'college_id')
    op.drop_column('announcements', 'details')
    # ### end Alembic commands ###
