"""telemetry_strikes_multi_tenancy

Revision ID: 3f1d52a01d43
Revises: e2b43de21ccd
Create Date: 2026-04-10 10:47:59.477514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1d52a01d43'
down_revision: Union[str, Sequence[str], None] = 'e2b43de21ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_event_registrations', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_alumni_event_registrations_college_id'), 'alumni_event_registrations', ['college_id'], unique=False)
    op.create_foreign_key(None, 'alumni_event_registrations', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('appeals', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_appeals_college_id'), 'appeals', ['college_id'], unique=False)
    op.create_foreign_key(None, 'appeals', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('challenge_progress', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_challenge_progress_college_id'), 'challenge_progress', ['college_id'], unique=False)
    op.create_foreign_key(None, 'challenge_progress', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('course_enrollments', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_course_enrollments_college_id'), 'course_enrollments', ['college_id'], unique=False)
    op.create_foreign_key(None, 'course_enrollments', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('mark_submission_entries', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_mark_submission_entries_college_id'), 'mark_submission_entries', ['college_id'], unique=False)
    op.create_foreign_key(None, 'mark_submission_entries', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('proctoring_events', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_proctoring_events_college_id'), 'proctoring_events', ['college_id'], unique=False)
    op.create_foreign_key(None, 'proctoring_events', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('proctoring_violations', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_proctoring_violations_college_id'), 'proctoring_violations', ['college_id'], unique=False)
    op.create_foreign_key(None, 'proctoring_violations', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_attempts', sa.Column('telemetry_strikes', sa.Integer(), nullable=False, server_default='0'))
    
    # Backfill missing college_ids before enforcing nullable=False
    op.execute("UPDATE users SET college_id = (SELECT id FROM colleges LIMIT 1) WHERE college_id IS NULL AND EXISTS(SELECT 1 FROM colleges)")
    
    op.alter_column('users', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('quiz_attempts', 'telemetry_strikes')
    op.drop_constraint(None, 'proctoring_violations', type_='foreignkey')
    op.drop_index(op.f('ix_proctoring_violations_college_id'), table_name='proctoring_violations')
    op.drop_column('proctoring_violations', 'college_id')
    op.drop_constraint(None, 'proctoring_events', type_='foreignkey')
    op.drop_index(op.f('ix_proctoring_events_college_id'), table_name='proctoring_events')
    op.drop_column('proctoring_events', 'college_id')
    op.drop_constraint(None, 'mark_submission_entries', type_='foreignkey')
    op.drop_index(op.f('ix_mark_submission_entries_college_id'), table_name='mark_submission_entries')
    op.drop_column('mark_submission_entries', 'college_id')
    op.drop_constraint(None, 'course_enrollments', type_='foreignkey')
    op.drop_index(op.f('ix_course_enrollments_college_id'), table_name='course_enrollments')
    op.drop_column('course_enrollments', 'college_id')
    op.drop_constraint(None, 'challenge_progress', type_='foreignkey')
    op.drop_index(op.f('ix_challenge_progress_college_id'), table_name='challenge_progress')
    op.drop_column('challenge_progress', 'college_id')
    op.drop_constraint(None, 'appeals', type_='foreignkey')
    op.drop_index(op.f('ix_appeals_college_id'), table_name='appeals')
    op.drop_column('appeals', 'college_id')
    op.drop_constraint(None, 'alumni_event_registrations', type_='foreignkey')
    op.drop_index(op.f('ix_alumni_event_registrations_college_id'), table_name='alumni_event_registrations')
    op.drop_column('alumni_event_registrations', 'college_id')
    # ### end Alembic commands ###
