"""Add extra_data to MarkEntry

Revision ID: 41393979731f
Revises: 7afad13a6b11
Create Date: 2026-04-05 04:13:31.803045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41393979731f'
down_revision: Union[str, Sequence[str], None] = '7afad13a6b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mark_entries', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('mark_entries_course_id_fkey'), 'mark_entries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('mark_entries_course_id_fkey'), 'mark_entries', 'courses', ['course_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('mark_entries', 'extra_data')
    # ### end Alembic commands ###
