"""TPO Core Migration

Revision ID: 53ded20cb055
Revises: 75ca34654a12
Create Date: 2026-04-07 01:57:35.701577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53ded20cb055'
down_revision: Union[str, Sequence[str], None] = '75ca34654a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('hr_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('bond_typical', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_table('placement_drives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('drive_type', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('bond_period', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('stipend', sa.Float(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('eligibility_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linked_quiz_id', sa.String(), nullable=True),
    sa.Column('quiz_threshold', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_quiz_id'], ['quizzes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_drives_college_id'), 'placement_drives', ['college_id'], unique=False)
    op.create_index(op.f('ix_placement_drives_company_id'), 'placement_drives', ['company_id'], unique=False)
    op.create_index(op.f('ix_placement_drives_id'), 'placement_drives', ['id'], unique=False)
    op.create_index(op.f('ix_placement_drives_is_deleted'), 'placement_drives', ['is_deleted'], unique=False)
    op.create_table('placement_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('drive_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('round_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('offer_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drive_id'], ['placement_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_applications_college_id'), 'placement_applications', ['college_id'], unique=False)
    op.create_index(op.f('ix_placement_applications_drive_id'), 'placement_applications', ['drive_id'], unique=False)
    op.create_index(op.f('ix_placement_applications_id'), 'placement_applications', ['id'], unique=False)
    op.create_index(op.f('ix_placement_applications_is_deleted'), 'placement_applications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placement_applications_student_id'), 'placement_applications', ['student_id'], unique=False)
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_is_deleted'), table_name='placements')
    op.drop_table('placements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('college_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('package', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('placements_college_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('placements_pkey'))
    )
    op.create_index(op.f('ix_placements_is_deleted'), 'placements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    op.drop_index(op.f('ix_placement_applications_student_id'), table_name='placement_applications')
    op.drop_index(op.f('ix_placement_applications_is_deleted'), table_name='placement_applications')
    op.drop_index(op.f('ix_placement_applications_id'), table_name='placement_applications')
    op.drop_index(op.f('ix_placement_applications_drive_id'), table_name='placement_applications')
    op.drop_index(op.f('ix_placement_applications_college_id'), table_name='placement_applications')
    op.drop_table('placement_applications')
    op.drop_index(op.f('ix_placement_drives_is_deleted'), table_name='placement_drives')
    op.drop_index(op.f('ix_placement_drives_id'), table_name='placement_drives')
    op.drop_index(op.f('ix_placement_drives_company_id'), table_name='placement_drives')
    op.drop_index(op.f('ix_placement_drives_college_id'), table_name='placement_drives')
    op.drop_table('placement_drives')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
