"""add_parent_student_link_and_grievance

Revision ID: 540463a52b45
Revises: 5679791117be
Create Date: 2026-04-07 11:31:14.495629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540463a52b45'
down_revision: Union[str, Sequence[str], None] = '5679791117be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('submitted_by_role', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_college_id'), 'grievances', ['college_id'], unique=False)
    op.create_index(op.f('ix_grievances_id'), 'grievances', ['id'], unique=False)
    op.create_index(op.f('ix_grievances_is_deleted'), 'grievances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_grievances_submitted_by'), 'grievances', ['submitted_by'], unique=False)
    op.create_table('parent_student_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index(op.f('ix_parent_student_links_college_id'), 'parent_student_links', ['college_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_id'), 'parent_student_links', ['id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_is_deleted'), 'parent_student_links', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_parent_student_links_parent_id'), 'parent_student_links', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_links_student_id'), 'parent_student_links', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_student_links_student_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_parent_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_is_deleted'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_id'), table_name='parent_student_links')
    op.drop_index(op.f('ix_parent_student_links_college_id'), table_name='parent_student_links')
    op.drop_table('parent_student_links')
    op.drop_index(op.f('ix_grievances_submitted_by'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_is_deleted'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_college_id'), table_name='grievances')
    op.drop_table('grievances')
    # ### end Alembic commands ###
