"""add_alumni_module_8_tables

Revision ID: 5679791117be
Revises: 53ded20cb055
Create Date: 2026-04-07 10:09:45.954620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5679791117be'
down_revision: Union[str, Sequence[str], None] = '53ded20cb055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('proof_url', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_achievements_alumni_id'), 'alumni_achievements', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_alumni_achievements_college_id'), 'alumni_achievements', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_achievements_id'), 'alumni_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_achievements_is_deleted'), 'alumni_achievements', ['is_deleted'], unique=False)
    op.create_table('alumni_contributions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=False),
    sa.Column('contribution_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('acknowledgment_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_contributions_alumni_id'), 'alumni_contributions', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_alumni_contributions_college_id'), 'alumni_contributions', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_contributions_id'), 'alumni_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_contributions_is_deleted'), 'alumni_contributions', ['is_deleted'], unique=False)
    op.create_table('alumni_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), server_default='published', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_events_college_id'), 'alumni_events', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_events_id'), 'alumni_events', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_events_is_deleted'), 'alumni_events', ['is_deleted'], unique=False)
    op.create_table('alumni_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_feedback_college_id'), 'alumni_feedback', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_feedback_id'), 'alumni_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_feedback_is_deleted'), 'alumni_feedback', ['is_deleted'], unique=False)
    op.create_table('alumni_job_postings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ctc_range', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('eligibility', sa.String(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('referral_note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending_approval', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_job_postings_alumni_id'), 'alumni_job_postings', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_alumni_job_postings_college_id'), 'alumni_job_postings', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_job_postings_id'), 'alumni_job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_job_postings_is_deleted'), 'alumni_job_postings', ['is_deleted'], unique=False)
    op.create_table('alumni_mentorships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='requested', nullable=False),
    sa.Column('focus_area', sa.String(), nullable=True),
    sa.Column('session_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_mentorships_alumni_id'), 'alumni_mentorships', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_alumni_mentorships_college_id'), 'alumni_mentorships', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_mentorships_id'), 'alumni_mentorships', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_mentorships_is_deleted'), 'alumni_mentorships', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alumni_mentorships_student_id'), 'alumni_mentorships', ['student_id'], unique=False)
    op.create_table('alumni_event_registrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=False),
    sa.Column('rsvp_status', sa.String(), server_default='attending', nullable=False),
    sa.Column('attended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['alumni_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'alumni_id', name='uq_event_alumni')
    )
    op.create_index(op.f('ix_alumni_event_registrations_alumni_id'), 'alumni_event_registrations', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_alumni_event_registrations_event_id'), 'alumni_event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_alumni_event_registrations_id'), 'alumni_event_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_event_registrations_is_deleted'), 'alumni_event_registrations', ['is_deleted'], unique=False)
    op.create_table('alumni_guest_lectures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('alumni_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='invited', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alumni_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_guest_lectures_alumni_id'), 'alumni_guest_lectures', ['alumni_id'], unique=False)
    op.create_index(op.f('ix_alumni_guest_lectures_college_id'), 'alumni_guest_lectures', ['college_id'], unique=False)
    op.create_index(op.f('ix_alumni_guest_lectures_department_id'), 'alumni_guest_lectures', ['department_id'], unique=False)
    op.create_index(op.f('ix_alumni_guest_lectures_id'), 'alumni_guest_lectures', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_guest_lectures_is_deleted'), 'alumni_guest_lectures', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumni_guest_lectures_is_deleted'), table_name='alumni_guest_lectures')
    op.drop_index(op.f('ix_alumni_guest_lectures_id'), table_name='alumni_guest_lectures')
    op.drop_index(op.f('ix_alumni_guest_lectures_department_id'), table_name='alumni_guest_lectures')
    op.drop_index(op.f('ix_alumni_guest_lectures_college_id'), table_name='alumni_guest_lectures')
    op.drop_index(op.f('ix_alumni_guest_lectures_alumni_id'), table_name='alumni_guest_lectures')
    op.drop_table('alumni_guest_lectures')
    op.drop_index(op.f('ix_alumni_event_registrations_is_deleted'), table_name='alumni_event_registrations')
    op.drop_index(op.f('ix_alumni_event_registrations_id'), table_name='alumni_event_registrations')
    op.drop_index(op.f('ix_alumni_event_registrations_event_id'), table_name='alumni_event_registrations')
    op.drop_index(op.f('ix_alumni_event_registrations_alumni_id'), table_name='alumni_event_registrations')
    op.drop_table('alumni_event_registrations')
    op.drop_index(op.f('ix_alumni_mentorships_student_id'), table_name='alumni_mentorships')
    op.drop_index(op.f('ix_alumni_mentorships_is_deleted'), table_name='alumni_mentorships')
    op.drop_index(op.f('ix_alumni_mentorships_id'), table_name='alumni_mentorships')
    op.drop_index(op.f('ix_alumni_mentorships_college_id'), table_name='alumni_mentorships')
    op.drop_index(op.f('ix_alumni_mentorships_alumni_id'), table_name='alumni_mentorships')
    op.drop_table('alumni_mentorships')
    op.drop_index(op.f('ix_alumni_job_postings_is_deleted'), table_name='alumni_job_postings')
    op.drop_index(op.f('ix_alumni_job_postings_id'), table_name='alumni_job_postings')
    op.drop_index(op.f('ix_alumni_job_postings_college_id'), table_name='alumni_job_postings')
    op.drop_index(op.f('ix_alumni_job_postings_alumni_id'), table_name='alumni_job_postings')
    op.drop_table('alumni_job_postings')
    op.drop_index(op.f('ix_alumni_feedback_is_deleted'), table_name='alumni_feedback')
    op.drop_index(op.f('ix_alumni_feedback_id'), table_name='alumni_feedback')
    op.drop_index(op.f('ix_alumni_feedback_college_id'), table_name='alumni_feedback')
    op.drop_table('alumni_feedback')
    op.drop_index(op.f('ix_alumni_events_is_deleted'), table_name='alumni_events')
    op.drop_index(op.f('ix_alumni_events_id'), table_name='alumni_events')
    op.drop_index(op.f('ix_alumni_events_college_id'), table_name='alumni_events')
    op.drop_table('alumni_events')
    op.drop_index(op.f('ix_alumni_contributions_is_deleted'), table_name='alumni_contributions')
    op.drop_index(op.f('ix_alumni_contributions_id'), table_name='alumni_contributions')
    op.drop_index(op.f('ix_alumni_contributions_college_id'), table_name='alumni_contributions')
    op.drop_index(op.f('ix_alumni_contributions_alumni_id'), table_name='alumni_contributions')
    op.drop_table('alumni_contributions')
    op.drop_index(op.f('ix_alumni_achievements_is_deleted'), table_name='alumni_achievements')
    op.drop_index(op.f('ix_alumni_achievements_id'), table_name='alumni_achievements')
    op.drop_index(op.f('ix_alumni_achievements_college_id'), table_name='alumni_achievements')
    op.drop_index(op.f('ix_alumni_achievements_alumni_id'), table_name='alumni_achievements')
    op.drop_table('alumni_achievements')
    # ### end Alembic commands ###
