"""Add Expert Models

Revision ID: 585b428a3049
Revises: a3c7fe8042b6
Create Date: 2026-04-07 22:24:04.943602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585b428a3049'
down_revision: Union[str, Sequence[str], None] = 'a3c7fe8042b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_paper_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('paper_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='submitted', nullable=False),
    sa.Column('expert_id', sa.String(), nullable=True),
    sa.Column('expert_comments', sa.String(), nullable=True),
    sa.Column('expert_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_paper_submissions_college_id'), 'question_paper_submissions', ['college_id'], unique=False)
    op.create_index(op.f('ix_question_paper_submissions_id'), 'question_paper_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_question_paper_submissions_is_deleted'), 'question_paper_submissions', ['is_deleted'], unique=False)
    op.create_table('study_materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='submitted', nullable=False),
    sa.Column('expert_id', sa.String(), nullable=True),
    sa.Column('expert_comments', sa.String(), nullable=True),
    sa.Column('expert_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_materials_college_id'), 'study_materials', ['college_id'], unique=False)
    op.create_index(op.f('ix_study_materials_id'), 'study_materials', ['id'], unique=False)
    op.create_index(op.f('ix_study_materials_is_deleted'), 'study_materials', ['is_deleted'], unique=False)
    op.create_table('teaching_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('expert_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('content_coverage_rating', sa.Integer(), nullable=False),
    sa.Column('methodology_rating', sa.Integer(), nullable=False),
    sa.Column('engagement_rating', sa.Integer(), nullable=False),
    sa.Column('assessment_quality_rating', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_evaluations_college_id'), 'teaching_evaluations', ['college_id'], unique=False)
    op.create_index(op.f('ix_teaching_evaluations_faculty_id'), 'teaching_evaluations', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_teaching_evaluations_id'), 'teaching_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_teaching_evaluations_is_deleted'), 'teaching_evaluations', ['is_deleted'], unique=False)
    op.create_table('expert_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('expert_user_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expert_user_id', 'college_id', 'subject_code', 'academic_year', name='uq_expert_assignment')
    )
    op.create_index(op.f('ix_expert_assignments_college_id'), 'expert_assignments', ['college_id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_expert_user_id'), 'expert_assignments', ['expert_user_id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_id'), 'expert_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_is_deleted'), 'expert_assignments', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_assignments_is_deleted'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_expert_user_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_college_id'), table_name='expert_assignments')
    op.drop_table('expert_assignments')
    op.drop_index(op.f('ix_teaching_evaluations_is_deleted'), table_name='teaching_evaluations')
    op.drop_index(op.f('ix_teaching_evaluations_id'), table_name='teaching_evaluations')
    op.drop_index(op.f('ix_teaching_evaluations_faculty_id'), table_name='teaching_evaluations')
    op.drop_index(op.f('ix_teaching_evaluations_college_id'), table_name='teaching_evaluations')
    op.drop_table('teaching_evaluations')
    op.drop_index(op.f('ix_study_materials_is_deleted'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_id'), table_name='study_materials')
    op.drop_index(op.f('ix_study_materials_college_id'), table_name='study_materials')
    op.drop_table('study_materials')
    op.drop_index(op.f('ix_question_paper_submissions_is_deleted'), table_name='question_paper_submissions')
    op.drop_index(op.f('ix_question_paper_submissions_id'), table_name='question_paper_submissions')
    op.drop_index(op.f('ix_question_paper_submissions_college_id'), table_name='question_paper_submissions')
    op.drop_table('question_paper_submissions')
    # ### end Alembic commands ###
