"""Add StudentFeeInvoice

Revision ID: 58da7c3a52d9
Revises: 99b57e3a1182
Create Date: 2026-04-09 18:08:18.088486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58da7c3a52d9'
down_revision: Union[str, Sequence[str], None] = '99b57e3a1182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_fee_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fee_invoices_college_id'), 'student_fee_invoices', ['college_id'], unique=False)
    op.create_index(op.f('ix_student_fee_invoices_id'), 'student_fee_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_student_fee_invoices_is_deleted'), 'student_fee_invoices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_student_fee_invoices_student_id'), 'student_fee_invoices', ['student_id'], unique=False)
    op.drop_table('nodal_officer_jurisdictions')
    op.drop_index(op.f('ix_expert_assignments_college_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_expert_user_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_is_deleted'), table_name='expert_assignments')
    op.drop_table('expert_assignments')
    op.execute("TRUNCATE TABLE fee_payments CASCADE")
    op.add_column('fee_payments', sa.Column('invoice_id', sa.String(), nullable=True))
    op.add_column('fee_payments', sa.Column('receipt_url', sa.String(), nullable=True))
    op.alter_column('fee_payments', 'invoice_id', nullable=False)
    op.drop_constraint(op.f('fee_payments_fee_template_id_fkey'), 'fee_payments', type_='foreignkey')
    op.create_foreign_key(None, 'fee_payments', 'student_fee_invoices', ['invoice_id'], ['id'], ondelete='NO ACTION')
    op.drop_column('fee_payments', 'fee_template_id')
    op.drop_index(op.f('ix_fee_templates_college_id'), table_name='fee_templates')
    op.drop_index(op.f('ix_fee_templates_id'), table_name='fee_templates')
    op.drop_index(op.f('ix_fee_templates_is_deleted'), table_name='fee_templates')
    op.drop_table('fee_templates')
    op.add_column('circular_acknowledgments', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('circular_acknowledgments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('circular_acknowledgments', 'circular_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circular_acknowledgments', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('circular_acknowledgments', 'acknowledged_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_circular_acknowledgments_id'), 'circular_acknowledgments', ['id'], unique=False)
    op.create_index(op.f('ix_circular_acknowledgments_is_deleted'), 'circular_acknowledgments', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('circular_acknowledgments_circular_id_fkey'), 'circular_acknowledgments', type_='foreignkey')
    op.drop_constraint(op.f('circular_acknowledgments_acknowledged_by_fkey'), 'circular_acknowledgments', type_='foreignkey')
    op.drop_constraint(op.f('circular_acknowledgments_college_id_fkey'), 'circular_acknowledgments', type_='foreignkey')
    op.create_foreign_key(None, 'circular_acknowledgments', 'dh_circulars', ['circular_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'circular_acknowledgments', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('dh_circulars', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('dh_circulars', 'issued_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_circulars', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_circulars', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dh_circulars', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_dh_circulars_id'), 'dh_circulars', ['id'], unique=False)
    op.drop_constraint(op.f('dh_circulars_issued_by_fkey'), 'dh_circulars', type_='foreignkey')
    op.drop_column('dh_circulars', 'deadline')
    op.drop_column('dh_circulars', 'issued_date')
    op.add_column('dh_submission_records', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('dh_submission_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('dh_submission_records', 'requirement_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_submission_records', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_submission_records', 'submitted_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_submission_records', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_dh_submission_records_id'), 'dh_submission_records', ['id'], unique=False)
    op.create_index(op.f('ix_dh_submission_records_is_deleted'), 'dh_submission_records', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('dh_submission_records_submitted_by_fkey'), 'dh_submission_records', type_='foreignkey')
    op.drop_constraint(op.f('dh_submission_records_college_id_fkey'), 'dh_submission_records', type_='foreignkey')
    op.drop_constraint(op.f('dh_submission_records_requirement_id_fkey'), 'dh_submission_records', type_='foreignkey')
    op.create_foreign_key(None, 'dh_submission_records', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dh_submission_records', 'dh_submission_requirements', ['requirement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dh_submission_records', 'submitted_at')
    op.drop_column('dh_submission_records', 'rejection_reason')
    op.add_column('dh_submission_requirements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('dh_submission_requirements', 'nodal_officer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_submission_requirements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_submission_requirements', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('dh_submission_requirements', 'data_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dh_submission_requirements', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_dh_submission_requirements_id'), 'dh_submission_requirements', ['id'], unique=False)
    op.drop_constraint(op.f('dh_submission_requirements_nodal_officer_id_fkey'), 'dh_submission_requirements', type_='foreignkey')
    # fee_payments changes moved up
    op.add_column('inspection_records', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('inspection_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('inspection_records', 'nodal_officer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspection_records', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspection_records', 'inspection_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               nullable=False)
    op.alter_column('inspection_records', 'inspection_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspection_records', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_inspection_records_id'), 'inspection_records', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_records_is_deleted'), 'inspection_records', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('inspection_records_college_id_fkey'), 'inspection_records', type_='foreignkey')
    op.drop_constraint(op.f('inspection_records_nodal_officer_id_fkey'), 'inspection_records', type_='foreignkey')
    op.create_foreign_key(None, 'inspection_records', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('inspection_responses', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('inspection_responses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('inspection_responses', 'inspection_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspection_responses', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspection_responses', 'response_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspection_responses', 'response_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_inspection_responses_id'), 'inspection_responses', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_responses_is_deleted'), 'inspection_responses', ['is_deleted'], unique=False)
    op.drop_constraint(op.f('inspection_responses_college_id_fkey'), 'inspection_responses', type_='foreignkey')
    op.drop_constraint(op.f('inspection_responses_inspection_id_fkey'), 'inspection_responses', type_='foreignkey')
    op.drop_constraint(op.f('inspection_responses_response_by_fkey'), 'inspection_responses', type_='foreignkey')
    op.create_foreign_key(None, 'inspection_responses', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inspection_responses', 'inspection_records', ['inspection_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_mark_entries_exam_type'), 'mark_entries', ['exam_type'], unique=False)
    op.create_foreign_key(None, 'mark_entries', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # op.execute("UPDATE users SET college_id = 'GNI' WHERE college_id IS NULL")
    # op.alter_column('users', 'college_id',
    #           existing_type=sa.VARCHAR(),
    #           nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'mark_entries', type_='foreignkey')
    op.drop_index(op.f('ix_mark_entries_exam_type'), table_name='mark_entries')
    op.drop_constraint(None, 'inspection_responses', type_='foreignkey')
    op.drop_constraint(None, 'inspection_responses', type_='foreignkey')
    op.create_foreign_key(op.f('inspection_responses_response_by_fkey'), 'inspection_responses', 'users', ['response_by'], ['id'])
    op.create_foreign_key(op.f('inspection_responses_inspection_id_fkey'), 'inspection_responses', 'inspection_records', ['inspection_id'], ['id'])
    op.create_foreign_key(op.f('inspection_responses_college_id_fkey'), 'inspection_responses', 'colleges', ['college_id'], ['id'])
    op.drop_index(op.f('ix_inspection_responses_is_deleted'), table_name='inspection_responses')
    op.drop_index(op.f('ix_inspection_responses_id'), table_name='inspection_responses')
    op.alter_column('inspection_responses', 'response_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('inspection_responses', 'response_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspection_responses', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspection_responses', 'inspection_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('inspection_responses', 'deleted_at')
    op.drop_column('inspection_responses', 'is_deleted')
    op.drop_constraint(None, 'inspection_records', type_='foreignkey')
    op.create_foreign_key(op.f('inspection_records_nodal_officer_id_fkey'), 'inspection_records', 'users', ['nodal_officer_id'], ['id'])
    op.create_foreign_key(op.f('inspection_records_college_id_fkey'), 'inspection_records', 'colleges', ['college_id'], ['id'])
    op.drop_index(op.f('ix_inspection_records_is_deleted'), table_name='inspection_records')
    op.drop_index(op.f('ix_inspection_records_id'), table_name='inspection_records')
    op.alter_column('inspection_records', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspection_records', 'inspection_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspection_records', 'inspection_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('inspection_records', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspection_records', 'nodal_officer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('inspection_records', 'deleted_at')
    op.drop_column('inspection_records', 'is_deleted')
    op.add_column('fee_payments', sa.Column('fee_template_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fee_payments', type_='foreignkey')
    op.create_foreign_key(op.f('fee_payments_fee_template_id_fkey'), 'fee_payments', 'fee_templates', ['fee_template_id'], ['id'])
    op.drop_column('fee_payments', 'receipt_url')
    op.drop_column('fee_payments', 'invoice_id')
    op.create_foreign_key(op.f('dh_submission_requirements_nodal_officer_id_fkey'), 'dh_submission_requirements', 'users', ['nodal_officer_id'], ['id'])
    op.drop_index(op.f('ix_dh_submission_requirements_id'), table_name='dh_submission_requirements')
    op.alter_column('dh_submission_requirements', 'deadline',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dh_submission_requirements', 'data_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dh_submission_requirements', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dh_submission_requirements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dh_submission_requirements', 'nodal_officer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('dh_submission_requirements', 'created_at')
    op.add_column('dh_submission_records', sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('dh_submission_records', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dh_submission_records', type_='foreignkey')
    op.drop_constraint(None, 'dh_submission_records', type_='foreignkey')
    op.create_foreign_key(op.f('dh_submission_records_requirement_id_fkey'), 'dh_submission_records', 'dh_submission_requirements', ['requirement_id'], ['id'])
    op.create_foreign_key(op.f('dh_submission_records_college_id_fkey'), 'dh_submission_records', 'colleges', ['college_id'], ['id'])
    op.create_foreign_key(op.f('dh_submission_records_submitted_by_fkey'), 'dh_submission_records', 'users', ['submitted_by'], ['id'])
    op.drop_index(op.f('ix_dh_submission_records_is_deleted'), table_name='dh_submission_records')
    op.drop_index(op.f('ix_dh_submission_records_id'), table_name='dh_submission_records')
    op.alter_column('dh_submission_records', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dh_submission_records', 'submitted_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dh_submission_records', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dh_submission_records', 'requirement_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('dh_submission_records', 'deleted_at')
    op.drop_column('dh_submission_records', 'is_deleted')
    op.add_column('dh_circulars', sa.Column('issued_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('dh_circulars', sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('dh_circulars_issued_by_fkey'), 'dh_circulars', 'users', ['issued_by'], ['id'])
    op.drop_index(op.f('ix_dh_circulars_id'), table_name='dh_circulars')
    op.alter_column('dh_circulars', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dh_circulars', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('dh_circulars', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dh_circulars', 'issued_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('dh_circulars', 'created_at')
    op.drop_constraint(None, 'circular_acknowledgments', type_='foreignkey')
    op.drop_constraint(None, 'circular_acknowledgments', type_='foreignkey')
    op.create_foreign_key(op.f('circular_acknowledgments_college_id_fkey'), 'circular_acknowledgments', 'colleges', ['college_id'], ['id'])
    op.create_foreign_key(op.f('circular_acknowledgments_acknowledged_by_fkey'), 'circular_acknowledgments', 'users', ['acknowledged_by'], ['id'])
    op.create_foreign_key(op.f('circular_acknowledgments_circular_id_fkey'), 'circular_acknowledgments', 'dh_circulars', ['circular_id'], ['id'])
    op.drop_index(op.f('ix_circular_acknowledgments_is_deleted'), table_name='circular_acknowledgments')
    op.drop_index(op.f('ix_circular_acknowledgments_id'), table_name='circular_acknowledgments')
    op.alter_column('circular_acknowledgments', 'acknowledged_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circular_acknowledgments', 'college_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('circular_acknowledgments', 'circular_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('circular_acknowledgments', 'deleted_at')
    op.drop_column('circular_acknowledgments', 'is_deleted')
    op.create_table('fee_templates',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('college_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fee_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('academic_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fee_templates_college_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('fee_templates_pkey'))
    )
    op.create_index(op.f('ix_fee_templates_is_deleted'), 'fee_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_fee_templates_id'), 'fee_templates', ['id'], unique=False)
    op.create_index(op.f('ix_fee_templates_college_id'), 'fee_templates', ['college_id'], unique=False)
    op.create_table('expert_assignments',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('college_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expert_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('academic_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('expert_assignments_assigned_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('expert_assignments_college_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('expert_assignments_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_user_id'], ['users.id'], name=op.f('expert_assignments_expert_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('expert_assignments_pkey')),
    sa.UniqueConstraint('expert_user_id', 'college_id', 'subject_code', 'academic_year', name=op.f('uq_expert_assignment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_expert_assignments_is_deleted'), 'expert_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_expert_assignments_id'), 'expert_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_expert_user_id'), 'expert_assignments', ['expert_user_id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_college_id'), 'expert_assignments', ['college_id'], unique=False)
    op.create_table('nodal_officer_jurisdictions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nodal_officer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('nodal_officer_jurisdictions_assigned_by_fkey')),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('nodal_officer_jurisdictions_college_id_fkey')),
    sa.ForeignKeyConstraint(['nodal_officer_id'], ['users.id'], name=op.f('nodal_officer_jurisdictions_nodal_officer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nodal_officer_jurisdictions_pkey'))
    )
    op.drop_index(op.f('ix_student_fee_invoices_student_id'), table_name='student_fee_invoices')
    op.drop_index(op.f('ix_student_fee_invoices_is_deleted'), table_name='student_fee_invoices')
    op.drop_index(op.f('ix_student_fee_invoices_id'), table_name='student_fee_invoices')
    op.drop_index(op.f('ix_student_fee_invoices_college_id'), table_name='student_fee_invoices')
    op.drop_table('student_fee_invoices')
    # ### end Alembic commands ###
