"""Add CodingChallenge and ChallengeProgress

Revision ID: 71be9e18a761
Revises: 57c31923df13
Create Date: 2026-04-05 18:16:41.487215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71be9e18a761'
down_revision: Union[str, Sequence[str], None] = '57c31923df13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language_support', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('init_code', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_challenges_id'), 'coding_challenges', ['id'], unique=False)
    op.create_table('challenge_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('language_used', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['coding_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_progress_challenge_id'), 'challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_progress_id'), 'challenge_progress', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_progress_student_id'), 'challenge_progress', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_progress_student_id'), table_name='challenge_progress')
    op.drop_index(op.f('ix_challenge_progress_id'), table_name='challenge_progress')
    op.drop_index(op.f('ix_challenge_progress_challenge_id'), table_name='challenge_progress')
    op.drop_table('challenge_progress')
    op.drop_index(op.f('ix_coding_challenges_id'), table_name='coding_challenges')
    op.drop_table('coding_challenges')
    # ### end Alembic commands ###
