"""Add Nodal Officer Models

Revision ID: 8d1877283b5a
Revises: 585b428a3049
Create Date: 2026-04-07 23:42:14.886892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d1877283b5a'
down_revision: Union[str, Sequence[str], None] = '585b428a3049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dh_circulars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issued_by', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('issued_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_colleges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dh_circulars_is_deleted'), 'dh_circulars', ['is_deleted'], unique=False)
    op.create_table('dh_submission_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nodal_officer_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_colleges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nodal_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dh_submission_requirements_is_deleted'), 'dh_submission_requirements', ['is_deleted'], unique=False)
    op.create_table('inspection_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nodal_officer_id', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_type', sa.String(), nullable=True),
    sa.Column('team_members', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['nodal_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodal_officer_jurisdictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nodal_officer_id', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['nodal_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circular_acknowledgments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circular_id', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['circular_id'], ['dh_circulars.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dh_submission_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submission_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['dh_submission_requirements.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inspection_id', sa.String(), nullable=True),
    sa.Column('college_id', sa.String(), nullable=True),
    sa.Column('response_by', sa.String(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_records.id'], ),
    sa.ForeignKeyConstraint(['response_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity_permissions', sa.Column('nodal_acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('activity_permissions', sa.Column('nodal_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_permissions', 'nodal_notes')
    op.drop_column('activity_permissions', 'nodal_acknowledged_at')
    op.drop_table('inspection_responses')
    op.drop_table('dh_submission_records')
    op.drop_table('circular_acknowledgments')
    op.drop_table('nodal_officer_jurisdictions')
    op.drop_table('inspection_records')
    op.drop_index(op.f('ix_dh_submission_requirements_is_deleted'), table_name='dh_submission_requirements')
    op.drop_table('dh_submission_requirements')
    op.drop_index(op.f('ix_dh_circulars_is_deleted'), table_name='dh_circulars')
    op.drop_table('dh_circulars')
    # ### end Alembic commands ###
