"""Add MarkSubmission and MarkSubmissionEntry

Revision ID: 8e6c9c747b99
Revises: af6d054a654b
Create Date: 2026-04-09 00:30:18.742715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e6c9c747b99'
down_revision: Union[str, Sequence[str], None] = 'af6d054a654b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_remarks', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['faculty_assignments.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mark_sub_fac_course_exam', 'mark_submissions', ['faculty_id', 'subject_code', 'exam_type'], unique=False)
    op.create_index(op.f('ix_mark_submissions_college_id'), 'mark_submissions', ['college_id'], unique=False)
    op.create_index(op.f('ix_mark_submissions_is_deleted'), 'mark_submissions', ['is_deleted'], unique=False)
    op.create_table('mark_submission_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['mark_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'student_id', name='uq_submission_student')
    )
    op.create_index(op.f('ix_mark_submission_entries_student_id'), 'mark_submission_entries', ['student_id'], unique=False)
    op.create_index(op.f('ix_mark_submission_entries_submission_id'), 'mark_submission_entries', ['submission_id'], unique=False)
    op.create_index(op.f('ix_rls_shadow_logs_id'), 'rls_shadow_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rls_shadow_logs_id'), table_name='rls_shadow_logs')
    op.drop_index(op.f('ix_mark_submission_entries_submission_id'), table_name='mark_submission_entries')
    op.drop_index(op.f('ix_mark_submission_entries_student_id'), table_name='mark_submission_entries')
    op.drop_table('mark_submission_entries')
    op.drop_index(op.f('ix_mark_submissions_is_deleted'), table_name='mark_submissions')
    op.drop_index(op.f('ix_mark_submissions_college_id'), table_name='mark_submissions')
    op.drop_index('ix_mark_sub_fac_course_exam', table_name='mark_submissions')
    op.drop_table('mark_submissions')
    # ### end Alembic commands ###
