"""add_quiz_child_college_ids

Revision ID: 982e5ce3d268
Revises: 999fa6c84a81
Create Date: 2026-04-08 14:32:45.121836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982e5ce3d268'
down_revision: Union[str, Sequence[str], None] = '999fa6c84a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_options_college_id'), 'options', ['college_id'], unique=False)
    op.create_foreign_key(None, 'options', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('questions', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_questions_college_id'), 'questions', ['college_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_answers', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_quiz_answers_college_id'), 'quiz_answers', ['college_id'], unique=False)
    op.create_foreign_key(None, 'quiz_answers', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_attempts', sa.Column('college_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_quiz_attempts_college_id'), 'quiz_attempts', ['college_id'], unique=False)
    op.create_foreign_key(None, 'quiz_attempts', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    # ### Backfill college_id for denormalized tables ###
    op.execute("UPDATE questions SET college_id = q.college_id FROM quizzes q WHERE questions.quiz_id = q.id")
    op.execute("UPDATE options SET college_id = q.college_id FROM questions q WHERE options.question_id = q.id")
    op.execute("UPDATE quiz_attempts SET college_id = q.college_id FROM quizzes q WHERE quiz_attempts.quiz_id = q.id")
    op.execute("UPDATE quiz_answers SET college_id = qa.college_id FROM quiz_attempts qa WHERE quiz_answers.attempt_id = qa.id")
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_attempts_college_id'), table_name='quiz_attempts')
    op.drop_column('quiz_attempts', 'college_id')
    op.drop_constraint(None, 'quiz_answers', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_answers_college_id'), table_name='quiz_answers')
    op.drop_column('quiz_answers', 'college_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_college_id'), table_name='questions')
    op.drop_column('questions', 'college_id')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_index(op.f('ix_options_college_id'), table_name='options')
    op.drop_column('options', 'college_id')
    # ### end Alembic commands ###
