"""Add nodal models

Revision ID: 999fa6c84a81
Revises: 2e45e2cc5e6d
Create Date: 2026-04-08 11:07:35.370485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999fa6c84a81'
down_revision: Union[str, Sequence[str], None] = '2e45e2cc5e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mark_entries', 'student_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mark_entries', 'student_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
