"""Add roll_number to UserProfile

Revision ID: 9ae14c048bca
Revises: b6034343b30d
Create Date: 2026-04-11 12:13:33.462352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae14c048bca'
down_revision: Union[str, Sequence[str], None] = 'b6034343b30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('roll_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_profiles_roll_number'), 'user_profiles', ['roll_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_roll_number'), table_name='user_profiles')
    op.drop_column('user_profiles', 'roll_number')
    # ### end Alembic commands ###
