"""add_industry_module

Revision ID: eb44ad8be8c6
Revises: 540463a52b45
Create Date: 2026-04-07 12:45:58.863070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb44ad8be8c6'
down_revision: Union[str, Sequence[str], None] = '540463a52b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('performance_rating', sa.Integer(), nullable=False),
    sa.Column('technical_skills_rating', sa.Integer(), nullable=False),
    sa.Column('soft_skills_rating', sa.Integer(), nullable=False),
    sa.Column('overall_feedback', sa.String(), nullable=False),
    sa.Column('feedback_period', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_feedback_college_id'), 'employer_feedback', ['college_id'], unique=False)
    op.create_index(op.f('ix_employer_feedback_company_id'), 'employer_feedback', ['company_id'], unique=False)
    op.create_index(op.f('ix_employer_feedback_id'), 'employer_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_employer_feedback_is_deleted'), 'employer_feedback', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employer_feedback_student_id'), 'employer_feedback', ['student_id'], unique=False)
    op.create_table('industry_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('proposed_by', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('stipend_if_any', sa.Float(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='proposed', nullable=False),
    sa.Column('faculty_supervisor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_projects_college_id'), 'industry_projects', ['college_id'], unique=False)
    op.create_index(op.f('ix_industry_projects_company_id'), 'industry_projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_industry_projects_id'), 'industry_projects', ['id'], unique=False)
    op.create_index(op.f('ix_industry_projects_is_deleted'), 'industry_projects', ['is_deleted'], unique=False)
    op.create_table('mous',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mous_college_id'), 'mous', ['college_id'], unique=False)
    op.create_index(op.f('ix_mous_company_id'), 'mous', ['company_id'], unique=False)
    op.create_index(op.f('ix_mous_id'), 'mous', ['id'], unique=False)
    op.create_index(op.f('ix_mous_is_deleted'), 'mous', ['is_deleted'], unique=False)
    op.create_table('curriculum_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('feedback_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='submitted', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_feedback_college_id'), 'curriculum_feedback', ['college_id'], unique=False)
    op.create_index(op.f('ix_curriculum_feedback_id'), 'curriculum_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_curriculum_feedback_is_deleted'), 'curriculum_feedback', ['is_deleted'], unique=False)
    op.create_table('industry_project_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='applied', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['industry_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'student_id', name='uq_project_student_application')
    )
    op.create_index(op.f('ix_industry_project_applications_college_id'), 'industry_project_applications', ['college_id'], unique=False)
    op.create_index(op.f('ix_industry_project_applications_id'), 'industry_project_applications', ['id'], unique=False)
    op.create_index(op.f('ix_industry_project_applications_is_deleted'), 'industry_project_applications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_industry_project_applications_project_id'), 'industry_project_applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_industry_project_applications_student_id'), 'industry_project_applications', ['student_id'], unique=False)
    op.add_column('alumni_events', sa.Column('source_type', sa.String(), server_default='alumni', nullable=False))
    op.add_column('alumni_events', sa.Column('source_id', sa.String(), nullable=True))

    # --- DATA MIGRATION FOR MOUs ---
    conn = op.get_bind()
    import uuid
    import json
    
    res = conn.execute(sa.text("SELECT college_id, mous FROM institution_profiles WHERE mous IS NOT NULL AND jsonb_array_length(mous) > 0"))
    profiles = res.fetchall()
    
    mous_count = conn.execute(sa.text("SELECT COUNT(*) FROM mous")).scalar()
    
    if mous_count == 0 and profiles:
        for profile in profiles:
            college_id = profile[0]
            mous_list = profile[1] if isinstance(profile[1], list) else json.loads(profile[1])
            
            for mou_data in mous_list:
                company_name = mou_data.get('partner_name', mou_data.get('company_name', 'Unknown Partner'))
                
                company_res = conn.execute(sa.text("SELECT id FROM companies WHERE college_id = :college_id AND name = :name LIMIT 1"), {"college_id": college_id, "name": company_name}).first()
                if company_res:
                    company_id = company_res[0]
                else:
                    company_id = str(uuid.uuid4())
                    conn.execute(sa.text("""
                        INSERT INTO companies (id, college_id, name) 
                        VALUES (:id, :college_id, :name)
                    """), {"id": company_id, "college_id": college_id, "name": company_name})
                
                mou_id = str(uuid.uuid4())
                purpose = mou_data.get('purpose', 'General MOU')
                signed_date = mou_data.get('signed_date', '2020-01-01')
                valid_until = mou_data.get('valid_until', '2030-01-01')
                status = mou_data.get('status', 'active')
                document_url = mou_data.get('document_url', '')
                
                conn.execute(sa.text("""
                    INSERT INTO mous (id, college_id, company_id, purpose, signed_date, valid_until, status, document_url, benefits)
                    VALUES (:id, :college_id, :company_id, :purpose, :signed_date, :valid_until, :status, :document_url, :benefits)
                """), {
                    "id": mou_id, "college_id": college_id, "company_id": company_id,
                    "purpose": purpose, "signed_date": signed_date, "valid_until": valid_until,
                    "status": status, "document_url": document_url, "benefits": json.dumps(mou_data)
                })

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumni_events', 'source_id')
    op.drop_column('alumni_events', 'source_type')
    op.drop_index(op.f('ix_industry_project_applications_student_id'), table_name='industry_project_applications')
    op.drop_index(op.f('ix_industry_project_applications_project_id'), table_name='industry_project_applications')
    op.drop_index(op.f('ix_industry_project_applications_is_deleted'), table_name='industry_project_applications')
    op.drop_index(op.f('ix_industry_project_applications_id'), table_name='industry_project_applications')
    op.drop_index(op.f('ix_industry_project_applications_college_id'), table_name='industry_project_applications')
    op.drop_table('industry_project_applications')
    op.drop_index(op.f('ix_curriculum_feedback_is_deleted'), table_name='curriculum_feedback')
    op.drop_index(op.f('ix_curriculum_feedback_id'), table_name='curriculum_feedback')
    op.drop_index(op.f('ix_curriculum_feedback_college_id'), table_name='curriculum_feedback')
    op.drop_table('curriculum_feedback')
    op.drop_index(op.f('ix_mous_is_deleted'), table_name='mous')
    op.drop_index(op.f('ix_mous_id'), table_name='mous')
    op.drop_index(op.f('ix_mous_company_id'), table_name='mous')
    op.drop_index(op.f('ix_mous_college_id'), table_name='mous')
    op.drop_table('mous')
    op.drop_index(op.f('ix_industry_projects_is_deleted'), table_name='industry_projects')
    op.drop_index(op.f('ix_industry_projects_id'), table_name='industry_projects')
    op.drop_index(op.f('ix_industry_projects_company_id'), table_name='industry_projects')
    op.drop_index(op.f('ix_industry_projects_college_id'), table_name='industry_projects')
    op.drop_table('industry_projects')
    op.drop_index(op.f('ix_employer_feedback_student_id'), table_name='employer_feedback')
    op.drop_index(op.f('ix_employer_feedback_is_deleted'), table_name='employer_feedback')
    op.drop_index(op.f('ix_employer_feedback_id'), table_name='employer_feedback')
    op.drop_index(op.f('ix_employer_feedback_company_id'), table_name='employer_feedback')
    op.drop_index(op.f('ix_employer_feedback_college_id'), table_name='employer_feedback')
    op.drop_table('employer_feedback')
    # ### end Alembic commands ###
