"""Add composite indexes

Revision ID: f5a451d78d16
Revises: 71be9e18a761
Create Date: 2026-04-05 19:43:32.335088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a451d78d16'
down_revision: Union[str, Sequence[str], None] = '71be9e18a761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fac_assign_t_c', 'faculty_assignments', ['teacher_id', 'college_id'], unique=False)
    op.create_index('ix_quiz_attempts_q_s_s', 'quiz_attempts', ['quiz_id', 'student_id', 'status'], unique=False)
    op.create_index('ix_sem_grades_s_s', 'semester_grades', ['student_id', 'semester'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sem_grades_s_s', table_name='semester_grades')
    op.drop_index('ix_quiz_attempts_q_s_s', table_name='quiz_attempts')
    op.drop_index('ix_fac_assign_t_c', table_name='faculty_assignments')
    # ### end Alembic commands ###
