"""Refactor Role to use permissions JSONB

Revision ID: fdf5c0a1ee2d
Revises: 96a52011eb59
Create Date: 2026-04-05 11:02:12.218221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdf5c0a1ee2d'
down_revision: Union[str, Sequence[str], None] = '96a52011eb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('roles', 'system_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('system_role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
