// Real subjects from GNITC R22 curriculum (extracted from semester result PDFs)
export const mockSubjects = [
  // ── Semester 1 (1-1) ──────────────────────────────────
  { code: "22BS0MA01", name: "Matrices and Calculus", department: "ET", semester: 1 },
  { code: "22BS0CH01", name: "Engineering Chemistry", department: "ET", semester: 1 },
  { code: "22ES0CS01", name: "Programming for Problem Solving", department: "ET", semester: 1 },
  { code: "22ES0EE01", name: "Basic Electrical Engineering", department: "ET", semester: 1 },
  { code: "22ES0ME02", name: "Computer Aided Engineering Graphics", department: "ET", semester: 1 },
  { code: "22HS0EN01", name: "English for Skill Enhancement", department: "ET", semester: 1 },
  { code: "22BS0CH02", name: "Engineering Chemistry Laboratory", department: "ET", semester: 1 },
  { code: "22ES0CS02", name: "Programming for Problem Solving Laboratory", department: "ET", semester: 1 },
  { code: "22ES0EE02", name: "Basic Electrical Engineering Laboratory", department: "ET", semester: 1 },
  { code: "22ES0ME01", name: "Engineering Workshop", department: "ET", semester: 1 },
  // ── Semester 2 (1-2) ──────────────────────────────────
  { code: "22BS0MA02", name: "Ordinary Differential Equations and Vector Calculus", department: "ET", semester: 2 },
  { code: "22BS0PH01", name: "Applied Physics", department: "ET", semester: 2 },
  { code: "22PC0CS01", name: "Elements of Computer Science & Engineering", department: "ET", semester: 2 },
  { code: "22ES0EC01", name: "Electronic Devices and Circuits", department: "ET", semester: 2 },
  { code: "22ES0EC02", name: "Digital Electronics", department: "ET", semester: 2 },
  { code: "22HS0EN02", name: "English Language and Communication Skills Laboratory", department: "ET", semester: 2 },
  { code: "22BS0PH02", name: "Applied Physics Laboratory", department: "ET", semester: 2 },
  { code: "22ES0IT01", name: "IT Workshop", department: "ET", semester: 2 },
  { code: "22ES0CS07", name: "Python Programming Laboratory", department: "ET", semester: 2 },
  { code: "22MC0CH03", name: "Environmental Science", department: "ET", semester: 2 },
  // ── Semester 3 (2-1) ──────────────────────────────────
  { code: "22BS0MA05", name: "Computer Oriented Statistical Methods", department: "ET", semester: 3 },
  { code: "22PC0DS01", name: "Data Structures", department: "ET", semester: 3 },
  { code: "22PC0DS02", name: "Computer Organization and Architecture", department: "ET", semester: 3 },
  { code: "22PC0DS03", name: "Object Oriented Programming through Java", department: "ET", semester: 3 },
  { code: "22PC0DS04", name: "Data Structures Lab", department: "ET", semester: 3 },
  { code: "22PC0DS05", name: "Object Oriented Programming through Java Lab", department: "ET", semester: 3 },
  { code: "22MC0EN04", name: "Gender Sensitization Lab", department: "ET", semester: 3 },
  // ── Semester 4 (2-2) ──────────────────────────────────
  { code: "22PC0DS06", name: "Discrete Mathematics", department: "ET", semester: 4 },
  { code: "22PC0DS07", name: "Operating Systems", department: "ET", semester: 4 },
  { code: "22PC0DS08", name: "Database Management Systems", department: "ET", semester: 4 },
  { code: "22PC0DS09", name: "Software Engineering", department: "ET", semester: 4 },
  { code: "22PC0DS10", name: "Operating Systems Lab", department: "ET", semester: 4 },
  { code: "22PC0DS11", name: "Database Management Systems Lab", department: "ET", semester: 4 },
  { code: "22SS0MB01", name: "Business Economics & Financial Analysis", department: "ET", semester: 4 },
  { code: "22SD0DS01", name: "Data Visualization - R Programming, Power BI", department: "ET", semester: 4 },
  // ── Semester 5 (3-1) ──────────────────────────────────
  { code: "22PC0DS12", name: "Algorithm Design and Analysis", department: "ET", semester: 5 },
  { code: "22PC0DS13", name: "Introduction to Data Science", department: "ET", semester: 5 },
  { code: "22PC0DS14", name: "Computer Networks", department: "ET", semester: 5 },
  { code: "22PE0DS1B", name: "Artificial Intelligence", department: "ET", semester: 5 },
  { code: "22PE0DS2D", name: "DevOps", department: "ET", semester: 5 },
  { code: "22PC0DS15", name: "R Programming Lab", department: "ET", semester: 5 },
  { code: "22PC0DS16", name: "Computer Networks Lab", department: "ET", semester: 5 },
  { code: "22HS0EN03", name: "Advanced Communication Skills Lab", department: "ET", semester: 5 },
  { code: "22SD0DS03", name: "ETL - Kafka / Talend", department: "ET", semester: 5 },
  { code: "22MC0MB03", name: "Intellectual Property Rights", department: "ET", semester: 5 },
  // ── Semester 6 (3-2) ──────────────────────────────────
  { code: "22PC0DS17", name: "Automata Theory and Compiler Design", department: "ET", semester: 6 },
  { code: "22PC0DS18", name: "Machine Learning", department: "ET", semester: 6 },
  { code: "22PC0DS19", name: "Big Data Analytics", department: "ET", semester: 6 },
  { code: "22PE0DS3A", name: "Software Testing Methodologies", department: "ET", semester: 6 },
  { code: "22OE0EE1A", name: "Renewable Energy Sources", department: "ET", semester: 6 },
  { code: "22PC0DS20", name: "Machine Learning Lab", department: "ET", semester: 6 },
  { code: "22PC0DS21", name: "Big Data Analytics Lab", department: "ET", semester: 6 },
  { code: "22PE0DS3F", name: "Software Testing Methodologies Lab", department: "ET", semester: 6 },
  { code: "22SD0DS02", name: "Full Stack Development", department: "ET", semester: 6 },
  { code: "22MC0MB01", name: "Constitution of India", department: "ET", semester: 6 },
  { code: "22SD0DS04", name: "Industrial Oriented Mini Project / Internship", department: "ET", semester: 6 },
  { code: "22PR0DS01", name: "Real-time Research Project / Field Based Project", department: "ET", semester: 6 },
];
